### ISSUE TITLE
Can't visualize realtime data with sample

### ISSUE THREAD

**Issue by timkoers** [filoe/cscore#256] opened 2017-07-13 16:19 UTC
I tried the WinformsVisualization sample to visualize the audio being played in realtime. When I click From Default Device I get the following error: https://pastebin.com/HTAXKieg

When trying my own code, and **bypassing** the Dataflow check, I get the following errror:
https://pastebin.com/YfZtmiAs

Which means: WrongEndpointType = 0x88890003.

Searching for that error code I found this (http://naudio.codeplex.com/discussions/246592, last post)

> 0x88890003 | AUDCLNT_E_WRONG_ENDPOINT_TYPE
> 
> Description : The AUDCLNT_STREAMFLAGS_LOOPBACK flag is set but the endpoint device is a capture device, not a rendering device.

How can I visualize the audio being played in realtime with this library?

**Comment by filoe** [comment] 2017-07-16 11:16
What are the properties of your audio device?
SampleRate, bitdepth, number of channels,...?
Is it possible to get the actual values passed to the `_audioClient.Initialize` method?

**Comment by timkoers** [comment] 2017-07-16 15:05
This the value of DeviceFormat during debugging in VS: 

ChannelsAvailable: 8|SampleRate: 192000|Bps: 3072000|BlockAlign: 16|BitsPerSample: 16|Encoding: Extensible

using (_capture = new WasapiCapture(true, AudioClientShareMode.Shared, 1))
                {
                    _capture.Device = Endpoint;
                    _capture.Initialize(); <-- This is where the exception occurs (from my custom code)
                    _capture.Start();
                }

**Comment by filoe** [comment] 2017-07-16 22:29
You must use a input device in combination with WasapiCapture OR an output device in combination with WasapiLoopbackCapture. Do not pass a latency of 1 ms. Use something like 100ms.

**Comment by timkoers** [comment] 2017-07-17 14:26
Something like this? (this doesn't work either) https://pastebin.com/dwtArGZY

using (_capture = new WasapiLoopbackCapture(100))
                {
                    _capture.Device = Endpoint;
                    _capture.Initialize();
                    _capture.Start();
                }

**Comment by filoe** [comment] 2017-07-22 22:30
Ok, it's quite hard to reproduce it.
Could you please send me the values of the parameters of the AudioClient.Initialize method which are actually used?

**Comment by timkoers** [comment] 2017-07-23 08:27
I can't really figure out what you are meaning with AudioClient.Initialize, but here is an overview just before the capture.Initialize() call. I noticed the WaveFormatTag is different in the capture instance then in the Endpoint instance. I changed it, and it crashed.
![cscore details](https://user-images.githubusercontent.com/4262725/28497865-241812c2-6f91-11e7-93b3-6f218cc31952.png)

It threw this exception with Extensible as WaveFormatTag:
![cscore details 2](https://user-images.githubusercontent.com/4262725/28497871-84b46702-6f91-11e7-86a0-dc010e584c38.png)

**Comment by timkoers** [comment] 2017-08-08 07:26
Any updates regarding this issue?

**Comment by filoe** [comment] 2017-08-08 08:35
Will have a look at it during werkend.

**Comment by filoe** [comment] 2017-08-13 10:33
Don't change anything. You're confusing me.
Just run the sample and if it crashes, send me the parameters passed here:
https://i.imgur.com/4O55SBe.png

**Comment by timkoers** [comment] 2017-08-16 14:20
Here you go!

https://pastebin.com/pzwzcJHY

**Comment by filoe** [comment] 2017-08-19 09:13
I'm sorry but I still can't reproduce it. I've applied to exactly the same format to my device and it passes.
Google gives does not show up with a single reference to your error. 
Does playback on your device work?
Is hnsBufferDuration and hnsPeriodicity the same?
Have you already played with the latency? Set it to 50 or 150, 300?
Try to choose a different defaultFormat in the construction of the WasapiLoopbackCapture:
- Try to pass the DeviceFormat (use exactly the Endpoint.DeviceFormat).
- Try to pass a format like `new WaveFormat(48000, 16, 2);`

I'm really sorry, but I absolutely can't reproduce it with exactly the same configuration. It is just a guessing of mine. Maybe the issue is located within the audio driver.

**Comment by timkoers** [comment] 2017-08-19 11:54
When selecting Dolby Atmos for Home Theather as Spatial sound, the exception is thrown. When I select to use no spatial sound, the program works.
I am using the NVIDIA Driver version 385.28 and the NVIDIA Audio Driver version 1.3.34.27

On page 18 of the [release notes](http://us.download.nvidia.com/Windows/385.28/385.28-win10-win8-win7-desktop-release-notes.pdf) of this driver version, is shows that Audio Extensions 
(such as was provided with Windows Media Center Edition) (whatever that might be) is unsupported at the Windows 7 drivers. I am using Windows 10, so I don't think that has got something to do with it.

Here is an overview of both Atmos **disabled**:
ChannelsAvailable: 2
SampleRate: 48000
Bps: 192000
BlockAlign: 4
BitsPerSample: 16
Encoding: Extensible

With Atmos **enabled**:
ChannelsAvailable: 8
SampleRate: 192000
Bps: 3072000
BlockAlign: 16
BitsPerSample: 16
Encoding: Extensible

Is the library able to handle a sample rate of 192kHz with 8 channels?

**Comment by filoe** [comment] 2017-08-19 20:27
It is able to handle it. I've set my device to 192kHz, 16 bit with 8 channels.
No problem. What do you mean by "When I select to use no spatial sound"?
Is it a different device or is a option which you can set on your device?

**Comment by timkoers** [comment] 2017-08-19 20:58
Disabled any surround sound processing, so stereo sound is outputted, and when needed (with movies and games, surround sound is outputted)

Here https://thenextweb.com/opinion/2017/01/05/dolby-atmos-windows-10-going-finally-bring-surround-sound-masses/ is an article about spatial sound in Windows 10 with Dolby Atmos. If you need some debug data, just ask what you need and I'll provide!

________________________________
Van: Florian Rosmann <notifications@github.com>
verzonden: 19 aug. 2017 22:27
Aan: filoe/cscore
Cc: timkoers; Author
Onderwerp: Re: [filoe/cscore] Can't visualize realtime data with sample (#256)


It is able to handle it. I've set my device to 192kHz, 16 bit with 8 channels.
No problem. What do you mean by "When I select to use no spatial sound"?
Is it a different device or is a option which you can set on your device?

**Comment by filoe** [comment] 2017-10-21 20:28
To be honest... I really really can't figure it out. 
There are no other issues, related to this.
I'll keep an eye on it but it seems to be problem related to the windows api, not cscore.

I'll close it for now. Feel free to reopen it, if needed.

**Closed by filoe** 2017-10-21 20:28 UTC
Labels: bug
