### ISSUE TITLE
WriteToWaveStream not working in Extensions.cs

### ISSUE THREAD

**Issue by dafedidi** [filoe/cscore#138] opened 2016-08-26 04:12 UTC
I found a strange bug while using this function. I get a disposed object of the stream that I give to the function. Digging in, I see that this functions send my stream in a WaveWriter with a using statement. At the end of such using, the WaveWriter is disposed and my stream is no longer available but disposed by the object. 

```
public static void WriteToWaveStream(this IWaveSource source, Stream stream)
        {
            if (source == null)
                throw new ArgumentNullException("source");
            if (stream == null)
                throw new ArgumentNullException("stream");
            if (!stream.CanWrite)
                throw new ArgumentException("Stream is not writeable.", "stream");

            using (var writer = new WaveWriter(stream, source.WaveFormat))
            {
                int read;
                var buffer = new byte[source.WaveFormat.BytesPerSecond];
                while ((read = source.Read(buffer, 0, buffer.Length)) > 0)
                {
                    writer.Write(buffer, 0, read);
                }
            }
}
```

And see 

 ```
protected virtual void Dispose(bool disposing)
        {
            if (_isDisposed) return;

            if (!disposing) return;
            
            try
            {
                _isDisposing = true;
                WriteHeader();
            }
            catch (Exception ex)
            {
                Debug.WriteLine("WaveWriter::Dispose: " + ex);
            }
            finally
            {
                if (_writer != null)
                {
                    _writer.Close();
                    _writer = null;
                }

                if (_stream != null)
                {
                    _stream.Close();
                    _stream = null;
                }

                _isDisposing = false;
            }
            
            
            _isDisposed = true;
}
```

Which give 

An unhandled exception of type 'System.ObjectDisposedException' occurred in mscorlib.dll

I can give you a code sample if you wish to test it.

**Comment by filoe** [comment] 2016-08-28 15:35
So the issue is, that the `stream` gets closed?
Should be fixed now.

**Closed by filoe** 2016-08-28 15:35 UTC

**Comment by dafedidi** [comment] 2016-08-28 18:47
Thank you very much :)
