### ISSUE TITLE
ArgumentNullException

### ISSUE THREAD

**Issue by joelamos** [filoe/cscore#137] opened 2016-08-24 07:24 UTC
I received this stack trace from a user of my program. I'm not able to reproduce the issue, but maybe this will have some significance to you:
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.Enter(Object obj)
   at CSCore.Win32.ComObject.Finalize()
```

**Comment by filoe** [comment] 2016-08-26 16:09
Thanks for reporting. 
I've got idea how that can happen. 
The `_lockObj` passed to `Monitor.Enter` gets initialized in the constructor and is marked as `readonly`. So it is not possible to set it to `null` anywhere. 
Since this class is used as base class of many objects, I would guess you don't have some snippet to reproduce it?

**Closed** 2016-09-18 09:33 UTC
Labels: bug, wontfix
